apiVersion: v1
kind: ConfigMap
metadata:
  name: url-shortener-config
  namespace: url-shortener
data:
  BASE_URL: "http://localhost:8080"
  ENVIRONMENT: "production"
  PORT: "8080"
  FRONTEND_API_URL: "http://url-shortener-service:80"
