apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secrets
  namespace: url-shortener
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VyOnBhc3N3b3JkQHBvc3RncmVzOjU0MzIvdXJsc2hvcnRlbmVyP3NzbG1vZGU9ZGlzYWJsZQ==
  REDIS_URL: cmVkaXM6Ly9yZWRpczozNjM3OQ==
